### ISSUE TITLE
forcing the identified device ?

### ISSUE THREAD

**Issue by jeromeetienne** [borismus/webvr-polyfill#105]
- i would like to force webvr-polyfill to behave on desktop, the same as in nexus5 or whatever
- i would like that to debug

is that possible ?

ps: great work on webvr-polyfill and on your blog to make vr tech more known! thanks :)

**Comment by cvan** [comment]
set `WebVRConfig.FORCE_ENABLE_VR = true` and make sure you load the Dev Tools and spoof your `User-Agent` (using the Dev Tools)

**Comment by jeromeetienne** [comment]
in this case, it is doing the job a little too well. aka it assumes stuff about the screen resolution. being the one of the mobile you spoof.

What i would like in fact is simply having distorted stereo on my desktop. is there a was to make desktop to "present" on desktop ?

**Comment by cvan** [comment]
> What i would like in fact is simply having distorted stereo on my desktop. is there a was to make desktop to "present" on desktop ?

with Firefox Nightly and [Chromium experimental builds](https://webvr.info/get-chrome/), yes

**Comment by jeromeetienne** [comment]
@cvan here im assuming you suggest with a physical device ? 

maybe i can define a display which match my desktop screen ?
