### ISSUE TITLE
Issue with current three.js v76 VREffect.js

### ISSUE THREAD

**Issue by jeromeetienne** [borismus/webvr-polyfill#107]
npm VREffect.js and github one are different which cause the following bug

- when using webvr-polyfill basic example, then clicking on 'VR' button, on a android mobile phone (nexus 5/7)
- the screen just go black (not showing any distorted stereo as it is supposed to be)
- if one use the VREffect.js from the github repo, instead of the npm version
- both version are indeed different, but i dunno know

**Comment by borismus** [comment]
Yes, there are bugs in the VREffect of the current r76 master branch. The
one checked into this repo is from dev branch. This should all be resolved
in r77.

**Comment by cvan** [comment]
Yep, use https://github.com/mrdoob/three.js/blob/dev/examples/js/effects/VREffect.js

**Comment by jeromeetienne** [comment]
excelent to know that is in check, thanks!
