### ISSUE TITLE
what about pointerlock control when running on desktop

### ISSUE THREAD

**Issue by jeromeetienne** [borismus/webvr-polyfill#115]
- currently when running on desktop, the controls is using VRControls.js
- it is fine but require click to move orientation
- got the usual limit at the border 

Why not using pointerlock ? it seems more natural desktop

**Comment by borismus** [comment]
We had this at one point. I'm open to adding it.

**Comment by jeromeetienne** [comment]
excelent, i will see how to include it and do a pull request

**Comment by jeromeetienne** [comment]
duplicate from #123
