### ISSUE TITLE
Chrome on Android, does not render after distortion.

### ISSUE THREAD

**Issue by AdaRoseEdwards** [borismus/webvr-polyfill#116]
I think this maybe a bug as it works on older chrome and desktop chrome but breaks on current android chrome.

I put together a simple demo with three.js and the webvr polyfill and it works fine on Chrome Desktop (50) and Samsung Browser on Android (Modified Chrome 44) but Chrome 50 on Android does not render the video when rendering for Cardboard.

Testing steps:
1. Open android chrome
2. https://ftlabs.github.io/three-sixty-video
3. Press play and wait for the video to start playing
4. Press the cardboard button, a black screen is displayed with the cardboard icons no distorted video.

What should be displayed:

Cardboard UI with distorted video.

Platform: Chrome 50, Samsung Galaxy S6.

**Comment by AdaRoseEdwards** [comment]
This is the error from the console: 
![image](https://cloud.githubusercontent.com/assets/4225330/15487301/130c1fe4-2101-11e6-8100-9c7558189799.png)

**Comment by OliwerLarsson** [comment]
Got a similar issue but mine doesn't work in the samsung browser but in firefox and works perfectly on ios.

<img width="1011" alt="screen shot 2016-05-31 at 11 19 42" src="https://cloud.githubusercontent.com/assets/5395484/15669776/4bc21a42-2722-11e6-8e88-b9996f815625.png">

I'm using a slightly customized version of http://threejs.org/examples/#webvr_panorama but using this one and adding the polyfill and manager gives me this error instead on android, yet it works perfect on ios

<img width="1019" alt="screen shot 2016-05-31 at 11 55 10" src="https://cloud.githubusercontent.com/assets/5395484/15670611/9fcd3550-2726-11e6-9b6b-ac36c80639fc.png">

**Comment by AdaRoseEdwards** [comment]
Seems to be fixed in latest. :)
