### ISSUE TITLE
mixed up warning messages

### ISSUE THREAD

**Issue by blq** [borismus/webvr-polyfill#117]
Minor. 
When the method `DeviceInfo.determineDevice_` uses fallback measurements it mixes up the console warning messages between iOS and Android.

**Comment by borismus** [comment]
Thanks, please submit a PR!

**Comment by jeromeetienne** [comment]
i did a pull request fixing this issue in #127

**Comment by jeromeetienne** [comment]
maybe we could close this bug, as the pullrequest got merged

**Comment by blq** [comment]
thanks for fixing!
