### ISSUE TITLE
mouse-keyboard-vr-display.js animating with setinterval

### ISSUE THREAD

**Issue by jeromeetienne** [borismus/webvr-polyfill#121]
- in [src/mouse-keyboard-vr-display.js](https://github.com/borismus/webvr-polyfill/blob/master/src/mouse-keyboard-vr-display.js), the angle animation is done with a setInterval
- see [this line](https://github.com/borismus/webvr-polyfill/blob/master/src/mouse-keyboard-vr-display.js#L116)

any reason not to use requestAnimationFrame here ?

**Comment by borismus** [comment]
Nope. Open to it.

**Comment by jeromeetienne** [comment]
excelent i did a pull request

**Comment by jeromeetienne** [comment]
my first contribution! :)

**Comment by borismus** [comment]
Thanks for that :)
