### ISSUE TITLE
Error handling when no match is found in device database

### ISSUE THREAD

**Issue by zvxryb** [borismus/webvr-polyfill#128]
When the solution fails to find a matching entry in the device database, it throws a "Failed to recalculate device parameters" exception and returns an invalid cardboard device.  The LG G5 and iPad are both devices which can reproduce this issue.  Expected result should be one of the following:

1. Return a cardboard device with canPresent capability set to false.
2. Return a cardboard device with reasonable fallback parameters (~5.1" 16:9 display)
3. Return no cardboard device.

**Comment by dustinkerstein** [comment]
@zvxryb Were you able to find a workaround for this? I am getting crashes on iPads which prevent the viewer from loading.

**Comment by borismus** [comment]
Current behavior is that there's a default fallback to a default Android / iOS phone size. Why are you trying to do this on an iPad? It won't work in VR, but should still work in magic window mode. Or are you seeing issues there?

**Comment by dustinkerstein** [comment]
Sorry, yeah I as talking about the magic window mode. However, I can no longer reproduce this for some reason. Please ignore my comment.

**Comment by borismus** [comment]
OK. Closing.
