### ISSUE TITLE
Chrome Dev Tools : Emulator Device Orientation Sensor

### ISSUE THREAD

**Issue by devasur** [borismus/webvr-polyfill#132]
Is there a way to make WebVR Polyfill work with the orientation sensor emulation?

![screenshot 2016-06-25 at 11 51 00 am](https://cloud.githubusercontent.com/assets/2506466/16355147/a4ea4d30-3acb-11e6-8fab-fd8feffe4e9a.png)

**Comment by borismus** [comment]
No, it relies on DeviceMotion, and DevTools doesn't emulate that. You could
build your own though. DeviceMotion events can be synthesized.
