### ISSUE TITLE
Support to more viewers

### ISSUE THREAD

**Issue by bklava** [borismus/webvr-polyfill#145]
In device-info.js there are some some inverseCoefficients and a TODO note about them:
// Inverse distortion coefficients.
// TODO: Calculate these from distortionCoefficients in the future.

Any guide on how to compute these inverseCoefficients from the distortionCoefficients?

**Comment by borismus** [comment]
See here: https://github.com/borismus/webvr-polyfill/blob/master/src/distortion/distortion.js
