### ISSUE TITLE
buffer_scale = 1 appears to still be downsampling

### ISSUE THREAD

**Issue by dustinkerstein** [borismus/webvr-polyfill#156]
I can visibly see the effect of lowering buffer_scale to something like .1 but even when I set it to 1 you can still clearly see aliasing as a result of downsampling.

Comparing the older [boilerplate webvr-polyfill.js](https://github.com/borismus/webvr-boilerplate/blob/master/node_modules/webvr-polyfill/build) and the [current webvr-polyfill.js](https://github.com/borismus/webvr-polyfill/tree/master/build) shows different behavior. The older boilerplate code does not exhibit this issue. However, I'd prefer to not use this older version for other reasons. 

Does this sound like a possible bug? If not, any clues on how to avoid downsampling would be appreciated.

Thanks,
Dustin

**Comment by borismus** [comment]
Can you provide an example of this?

**Comment by dustinkerstein** [comment]
Here is a example that uses a 2048x2048 video file as a texture - https://www.panomoments.com/m/2048 - The buffer_scale is currently set to 1 and it's using the latest polyfill.

Let me know if you're not able to reproduce. I am using a Galaxy S7 Edge.

Thanks,
Dustin

**Comment by dustinkerstein** [comment]
It looks like I'm unable to replicate using my Microsoft Surface Pro 2 (in forced VR mode).

**Comment by dustinkerstein** [comment]
@borismus were you able to replicate? I may swap over to the older polyfill sometime today or this weekend, but want to make sure you're able to see the issue before doing so.

**Comment by dustinkerstein** [comment]
FYI, I reverted back to the old polyfill so that above example will no longer have the issue. I will try to setup another demo page where it can be replicated later today.

**Comment by dustinkerstein** [comment]
Hmm, there's something odd going on. I tried to put together a simple version to share, but I am unable to replicate. I'll try to dig around a little, but is it possible that some CSS is causing strange interactions?

**Comment by borismus** [comment]
Everything is possible, but if you can't repro I'm going to close the issue.
