### ISSUE TITLE
PosePredictor never updates previousTimestampS

### ISSUE THREAD

**Issue by crowriot** [borismus/webvr-polyfill#159]
I was just looking through sension fusion source, learning how it works - and it seems that this.previousTimestampS is never updated except the first time getPrediction is run. 

Is this an issue or just me not understanding how it should work correctly? IMO, where this.previousQ.copy(currentQ); happens, also this.previousTimestampS should get set to timestampS.

**Comment by borismus** [comment]
Huh. You're right. I wonder what's up with that! Fixed in https://github.com/borismus/webvr-polyfill/commit/236166d77bfb0d92fd16676df420d7243b0b99bc
