### ISSUE TITLE
Touch causes URL bar to become visible in iOS

### ISSUE THREAD

**Issue by brianchirls** [borismus/webvr-polyfill#19]
iOS doesn't support proper fullscreen and instead scrolls the page down so the URL bar is no longer visible. Touching to rotate the VR view also causes the page to scroll making the URL bar visible again.

I think the solution to this is to cancel the event in the `touchstart` listener callback.

Disclaimer: I have only tested this on the iOS simulator, since I don't have an actual iPhone.

**Comment by borismus** [comment]
I don't believe that there is a way to prevent this.
