### ISSUE TITLE
Use npm modules instead of bundling three-math.js

### ISSUE THREAD

**Issue by deathcap** [borismus/webvr-polyfill#2]
Would there be interest in converting webvr-polyfill to use various NPM modules for math instead of the included https://github.com/borismus/webvr-polyfill/blob/master/src/three-math.js? E.g.:

https://www.npmjs.com/package/gl-vec2
https://www.npmjs.com/package/gl-vec3
https://www.npmjs.com/package/gl-matrix-quat
https://www.npmjs.com/package/gl-matrix

(started working on this at https://github.com/deathcap/webvr-polyfill/tree/gl-vec3, but very incomplete)

**Comment by borismus** [comment]
Definitely interest in further reducing the dependency on three.js. I took
the Mathy classes out of it wholesale, but in terms of code path, only
using a small fraction of the 2kb of code. It might be an easier change to
prune down three-math.js rather than re-write parts of the polyfill.

**Comment by borismus** [comment]
See @toji's recent commit to remove three-math and replace it with math-utils.
