### ISSUE TITLE
Keyboard Controls UX

### ISSUE THREAD

**Issue by ashconnell** [borismus/webvr-polyfill#21]
I suggest we add an option to disable the keydown listener that controls camera rotation. PointerLock and click-to-drag controls make the most sense on desktop, and this allows more complex environments to use their own keyboard events for positional movement systems.

``` js
WebVRConfig.KEYBOARD_CONTROLS = false; // default true (backward compatible)
```

``` js
// in MouseKeyboardPositionVRDevice()
if (WebVRConfig.KEYBOARD_CONTROLS !== false) {
  window.addEventListener('keydown', this.onKeyDown_.bind(this));
}
```

**Comment by borismus** [comment]
As a workaround, you could use `MOUSE_KEYBOARD_CONTROLS_DISABLED`, and bring OrbitalControls into the mix. 

Alternatively, could just disable keyboard navigation. I haven't really found that useful.
