### ISSUE TITLE
mouse-controls are attached to the window, behaviour should be configurable

### ISSUE THREAD

**Issue by bumblehead** [borismus/webvr-polyfill#23]
mouse-controls are attached to the window, behaviour should be configurable

https://github.com/borismus/webvr-polyfill/blob/master/src/mouse-keyboard-position-sensor-vr-device.js#L37-L40

When custom video controls such as a seek bar are created, mouse events from those bubble to the window causing unwanted camera movement. The element used here should be configurable and/or the methods bound to the window should be configurable.

As a work-around I've modified a local copy of this file with the following,
```javascript
MouseKeyboardPositionSensorVRDevice.prototype.onMouseDown_ = function(e) {
  var elem = (function (e) {
    var fn = function () {};
    if (typeof e === 'object' && e) {
      if ('target' in e) {
        fn = function (ev) {
          return ev.target;
        };
      } else if ('srcElement' in e) {
        fn = function (ev) {
          return ev.srcElement;
        };
      }
    }
    return fn(e);
  }(e));
  
  if (/canvas/i.test(elem.tagName)) {
    this.rotateStart.set(e.clientX, e.clientY);
    this.isDragging = true;
  }
};
```

**Comment by pindiespace** [comment]
Put that in a pull request! 

To really get rid of all the implicit document.body assumptions, you have to modify the polyfill, boilerplate, and VREffect.js. Also, the polyfill assumes there is one window, so if you try making multiple webgl windows, they all move with the mouse. To really make this work (for things like VR slideshows) will require a significant overhaul.

**Comment by iambumblehead** [comment]
I submitted a PR for some related issues. The PR was ignored and later closed.

https://github.com/borismus/webvr-boilerplate/pull/77#event-522438711

**Comment by borismus** [comment]
Please re-open as needed.
