### ISSUE TITLE
Version update needed

### ISSUE THREAD

**Issue by brianchirls** [borismus/webvr-polyfill#24]
The latest commit f5366c838e5330ecddc51ce218e6670accca05f2 has breaking changes, which webvr-boilerplate is depending on, but did not update the version. Please update bower.json and package.json so the latest version gets pulled by the respective package manager. Thanks.

**Comment by borismus** [comment]
Should be fixed.

**Comment by brianchirls** [comment]
Woo hoo! Thank you!
