### ISSUE TITLE
Possible to simulate movement without using a device, for example in Chrome?

### ISSUE THREAD

**Issue by supermoos** [borismus/webvr-polyfill#25]
Do you have any recommendations on simulating a device motion, without using an actual device?
Something that could work in chrome maybe? Possibly something along the lines of the accelorometer emulator built in to the devtools?

**Comment by borismus** [comment]
Would be nice, but not something I can realistically help with. /cc
@paulirish @repenaxa

**Comment by borismus** [comment]
Looks like you can do this with the latest devtools (in Canary). Not sure if this will work for DeviceMotion events, which we currently use.
<img width="292" alt="screen shot 2016-03-28 at 11 56 14 am" src="https://cloud.githubusercontent.com/assets/277632/14086861/2366bc7e-f4dc-11e5-86d2-a002902cd6a0.png">

**Comment by paulirish** [comment]
currently the emulation doesnt do devicemotion. only orientation​

**Comment by borismus** [comment]
Feature request!!
