### ISSUE TITLE
z-axis up

### ISSUE THREAD

**Issue by FreakTheMighty** [borismus/webvr-polyfill#29]
I'm having trouble figuring out how to get camera movement to behave correctly in a scene where the z axis is the vertical axis. When the scene loads, the camera is pointing down the z axis, which in my scene the floor. Can anyone point me and my camera in the right direction?

**Comment by borismus** [comment]
We make certain assumptions about the coordinate system. You can work around this. For example, you can attach VRControls to a dummy object, and make your camera the child of that dummy object.
