### ISSUE TITLE
Suggestion: Add webcam head tracking support when no VR headset is detected

### ISSUE THREAD

**Issue by akinnee** [borismus/webvr-polyfill#4]
If there's no VR headset, in addition to using the mouse and keyboard to turn and move, it would be really cool to use webcam head tracking to change perspective/viewing angle.

Example: http://topheman.github.io/parallax/

**Comment by borismus** [comment]
Great idea. 

This also brings up another point, which is that currently we only support one input device at a time. For example if we have an Oculus plugged in, we need to choose between that and mouse/keyboard look. Adding a camera 6DOF thing as an input only complicates this further.

That said, a camera-based tracker is totally worth implementing.

**Comment by akinnee** [comment]
I would definitely like to see the ability to use multiple inputs at once. For example, in a seated VR experience I may want to use the keyboard/mouse or a controller to move and turn but still use head tracking on top of that. This would work well with the keyboard/mouse + webcam head tracking as well.

**Comment by borismus** [comment]
This is now [here](https://github.com/borismus/webvr-polyfill/blob/master/src/webcam-position-sensor-vr-device.js), but having it be part of the polyfill always seems like the wrong thing.

Here's a demo: <http://goo.gl/7ezPr7>

**Comment by akinnee** [comment]
Cool! :D I think webcam head tracking is a valid polyfill when not wearing an HMD or other head tracking device. Your demo URL goes to a 404 page.

**Comment by borismus** [comment]
Oops, updated link: <https://googledrive.com/host/0B4Nj-yDXjBs_fmNpbDdKMGlvLWg4RU05eWdKWURSZWs0d0ZzYURCemtodTdKeVprYy0ySFE>

**Comment by akinnee** [comment]
^ Nice!
