### ISSUE TITLE
Remove src from .npmignore

### ISSUE THREAD

**Issue by brianchirls** [borismus/webvr-polyfill#44]
Would it be possible to add the source files back into the npm package? I found it very useful for making minor customizations.

I don't think there's much down side to including these files, since they're not very big and would not affect what's delivered to the browser for people who want to use the built file. This would not include node_modules.

Thanks

**Comment by borismus** [comment]
Not sure what you mean, src is not in .gitignore.

**Comment by ashconnell** [comment]
I think he meant `.npmignore`.

**Comment by brianchirls** [comment]
Sorry, yeah, I meant `.npmignore`.

**Comment by borismus** [comment]
Ah, I see. Including the source seems a bit odd since it can be found in this github repo too, wouldn't you say? Do other packages do this as well?

**Comment by brianchirls** [comment]
Yes, the source is in the github repo, but it's not accessible at all via npm. Even if you point npm to the git repo instead of the npm registry, it still obeys .gitignore and leaves out the source. So one would have to update the webvr-polyfill dependency manually, which is no good.

A lot of other packages do leave in the un-built source, though many of them probably just forgot to make a .gitignore in the first place. I think the ideal scenario is that when a library is built out of components that are useful individually (as yours is; well done), each component is made available as its own npm package, even if they're all in the same repo. But it's a lot of work, and I'm not asking that. Leaving the source in is a good compromise, with `main` still pointing to the built file.

For example, Cannon.js is doing this, as discussed [here](https://github.com/schteppe/cannon.js/pull/200). It's nice in case anyone wants to use their vector math or something like that.

**Comment by brianchirls** [comment]
Oh, there's another significant potential benefit:

There are a number of components that require `three-math`, which it looks like you've included manually. If you were to include it from the npm package, someone referencing the source files could alias it to the three.js package. That way they wouldn't need to double up on all that math code.

**Comment by borismus** [comment]
Alright, I basically don't care about keeping the src/ files in there or not, so will make this change. (By the way you're still saying `.gitignore` where you mean `.npmignore`, I think?)

**Comment by brianchirls** [comment]
Ugh, yeah, I don't know why I keep typing that. I'll change it for future reference.

...and thanks!
