### ISSUE TITLE
support Oculus

### ISSUE THREAD

**Issue by andreasplesch** [borismus/webvr-polyfill#45]
This is probably a stupid question but I could not find straight forward information on the relation between Oculus and webvr-polyfill.

Is the Oculus supported on regular FF (without vr enable) and Chrome (standard) ?

To me it looks like the Oculus is not supported, only mobile. Perhaps it is not even possible to support the Oculus currently since the the necessary browser support would only benefit a tiny percentage of users and is therefore only made available in special browsers ?

But if you need special browsers for Oculus support why then use the polyfill in the first place ? I am sure I am missing something.

Is the polyfill targeted at mobile (cardbox, Gear) only ?

Apologies for the confusion but I would be very thankful for any clarification.

**Comment by borismus** [comment]
The polyfill's intent is to provide WebVR support mostly in the mobile web case: iOS Safari and Chrome for Android, used in Cardboard. It also provides a reasonable fallback for desktop mode. 

If you are targeting Oculus, you will need a special WebVR browser build.

**Comment by andreasplesch** [comment]
Thanks for the clarification.
