### ISSUE TITLE
Consider using budo for local browserify development

### ISSUE THREAD

**Issue by cvan** [borismus/webvr-polyfill#48]
Instead of the `watch` script, it'd be nice to use [`budo`](https://github.com/mattdesl/budo) for local development. It starts a local dev server and supports an option to live reload the page whenever the browserify bundle changes.

**Comment by borismus** [comment]
I'd prefer to stick to the watch script as it stands. I run my own local apache which exposes all of my projects via `localhost/~smus/Projects/.` Bundling a webserver seems to prescriptive to me.
