### ISSUE TITLE
Add demo/example for testing purposes

### ISSUE THREAD

**Issue by cvan** [borismus/webvr-polyfill#50]
So functionality can be tested without having to integrate it with [`webvr-boilerplate`](https://github.com/borismus/webvr-boilerplate) - since some folks are using `webvr-polyfill` standalone or with three.js and `THREE.VREffect`.

**Comment by borismus** [comment]
Yes, definitely.

**Comment by borismus** [comment]
Ok, this is now available here: http://borismus.github.io/webvr-polyfill/examples/basic/
