### ISSUE TITLE
Samsung Gear VR as a cardboard viewer

### ISSUE THREAD

**Issue by abuisine** [borismus/webvr-polyfill#60]
While access to the samsung gear vr is limited through the Oculus platform, it is easy to disable the oculus platform autolaunch (which usually triggers when the smartphone is plugged to the gear vr).
It would therefore be nice to have a compatible cardboard viewer in polyfill to enable correct rendering.

**Comment by abuisine** [comment]
The settings (numbers) in a viewer are pretty unclear to me, but if someone can explain a bit, I am happy to iterate and test.

**Comment by njam** [comment]
This is what we're using. Values with "?" we haven't researched yet.

- Inter-lens distance (m): 0.06
- Distortion coefficient k1: 0.215
- Distortion coefficient k2: 0.215
- Field-of-view angle Outer (°): 50
- Field-of-view angle Inner (°): 50
- Field-of-view angle Top (°): 50
- Field-of-view angle Bottom (°): 50
- Screen to lens distance (m): ?
- Tray to lens distance (m): ?
- Vertical Alignment: ?

**Comment by brianchirls** [comment]
There's been some discussion about the GearVR on the WebVR Slack channel, and it's worth noting that the Samsung VR web browser will support the WebVR API pretty soon (can't say exactly when). When it does, it will handle distortion natively.

I'm not sure it's worth the effort to polyfill for that at this point, especially since you'd probably have to change up the detection code to determine the difference between a Samsung S6/S7/etc. running Cardboard and the same phone running in GearVR.

**Comment by njam** [comment]
> Samsung VR web browser will support the WebVR API

Very interesting! Thanks for sharing. cc @zazabe

I still think it's nice for users if they can use their normal browser, and launch VR experiences directly from there.

> the difference between a Samsung S6/S7/etc. running Cardboard and the same phone running in GearVR.

There are many different Cardboard viewers available and usually VR applications need ask the user what headset he is using anyway (or to scan a QR code to determine that).

**Comment by abuisine** [comment]
Thanks for the quick answers. I totally understand the lack of interest to add this given that the samsung browser will support webvr.
The interest to add this for firefox and chrome is effectively debatable as a native experience is (will be) available.

**Comment by idflood** [comment]
The Samsung VR web browser has now experimental support for webvr api (using deprecated API though) : D

https://mail.mozilla.org/pipermail/web-vr-discuss/2016-April/001054.html

**Comment by borismus** [comment]
Yes, in light of that, polyfill support for Gear VR browser is out of scope.

**Comment by baseten** [comment]
@njam did you come up with any values for the '?'s. We'd still like to use the GearVR in cardboard mode rather than native WebVR as the resolution is much better. Seems like Samsung is dramatically limiting what (our S7 at least) is capable of rendering.

**Comment by njam** [comment]
@baseten unfortunately can't help you with that.
Here are some good explanations about those values, I think you should be able to measure them yourself: https://vr.google.com/cardboard/viewerprofilegenerator/
