### ISSUE TITLE
Disabling distortion correction 

### ISSUE THREAD

**Issue by scottgarner** [borismus/webvr-polyfill#61]
`PREVENT_DISTORTION` was helpful in instances where the performance hit was noticeable and distortion wasn't an issue.

**Comment by scottgarner** [comment]
I did find this:

https://github.com/borismus/webvr-polyfill/blob/master/build/webvr-polyfill.js#L2324

Manually setting that seems to work after a quick test, but I'm not clear on the best way to access that variable from outside the library.

**Comment by jhclaura** [comment]
Agree to bring back the feature for performance boost!
Also bring back DISTORTION_BGCOLOR (Object) to change the background color used in the barrel distortion shader pass. Current is white. Thanks!

**Comment by borismus** [comment]
Shouldn't be white. Make sure you're using latest version

**Comment by jhclaura** [comment]
Yes my bad. My comment is edited.

**Comment by borismus** [comment]
Just realized that this is available as predistorted: true
