### ISSUE TITLE
Basic example: canvas in wrong position when fullscreen mode is entered

### ISSUE THREAD

**Issue by cvan** [borismus/webvr-polyfill#65]
1. Load http://borismus.github.io/webvr-polyfill/examples/basic/
2. Click the "Fullscreen" button
3. Notice this:
    ![screenshot 2016-04-04 22 11 28](https://cloud.githubusercontent.com/assets/203725/14271900/8ec3391c-fab2-11e5-9e70-76560de94ec6.png)

**Comment by crookookoo** [comment]
Gotta be related to this, on mobile Safari I'm getting this behavior:

1.After going to landscape mode the app is fullscreen and looks normal
2.Upon tapping VR mode button: bars appear on top and bottom + canvas jumps up. (VR mode does not turn on)
![img_1467](https://cloud.githubusercontent.com/assets/5522686/14282844/89d6d538-fb40-11e5-8fd9-9d1ef4517c89.PNG)
3. Tapping the VR button again turns on VR mode, but the canvas and bars stay in place.
![img_1468](https://cloud.githubusercontent.com/assets/5522686/14282870/bea2dd52-fb40-11e5-919e-58c29474691a.PNG)

**Comment by borismus** [comment]
@crookookoo Still no difference?

**Comment by cvan** [comment]
@borismus can you bump the `gh-pages` branch?
