### ISSUE TITLE
Basic example: Setting `WebVRConfig.FORCE_ENABLE_VR = true` causes cube to disappear

### ISSUE THREAD

**Issue by cvan** [borismus/webvr-polyfill#78]
For [`examples/basic/index.html`](https://github.com/borismus/webvr-polyfill/blob/f85999/examples/basic/index.html#L46)

**Comment by roetz** [comment]
I've the same problem in my project

**Comment by borismus** [comment]
Weird, I can't repro? Can you link me to an example?

**Comment by rocwind** [comment]
It's not reproducible after this commit: https://github.com/borismus/webvr-polyfill/commit/349394834fc3613c76ba8314a3a6ac121ea5c99c

I created this example (a copy of basic example + FORCE_ENABLE_VR) using v0.9.17:
https://jsfiddle.net/anv3t5kz/1/

OS: OS X 10.11.6
Browser: Chrome v52

**Comment by borismus** [comment]
Thanks!
