### ISSUE TITLE
Basic example: Fails if `navigator.getVRDevices` exists (in Firefox and older experimental Chromium WebVR builds)

### ISSUE THREAD

**Issue by cvan** [borismus/webvr-polyfill#79]
1. Open Firefox Nightly (or open `about:config` in an older version of Firefox and set `dom.vr.enabled` to `true`)
2. Load https://borismus.github.io/webvr-polyfill/examples/basic/
3. Notice the scene doesn't render because of a JS error: `TypeError: navigator.getVRDisplays is not a function    basic:97:1`

**Comment by cvan** [comment]
<img width="1404" alt="screenshot 2016-04-06 20 17 20" src="https://cloud.githubusercontent.com/assets/203725/14339608/d80570a8-fc34-11e5-9bb1-c4131ebc25f9.png">

**Comment by sohow** [comment]
yes, I have the same problem too

**Comment by borismus** [comment]
Please use latest Chrome builds. This won't be updated for pre-1.0 WebVR implementations.
