### ISSUE TITLE
Wrong variable name in polyfilled getVRDevices

### ISSUE THREAD

**Issue by brianchirls** [borismus/webvr-polyfill#88]
In [`WebVRPolyfill.prototype.getVRDevices`](https://github.com/borismus/webvr-polyfill/blob/master/src/webvr-polyfill.js#L145),
`self.devices.push(displays[i]);`

should be:
`self.devices.push(devices[i]);`

**Comment by borismus** [comment]
PRs are welcome. Thanks!
