### ISSUE TITLE
Allow to provide custom HMDVRDevice default

### ISSUE THREAD

**Issue by njam** [borismus/webvr-polyfill#9]
Currently `enablePolyfill` assumes that it's being used with a Cardboard device on all mobile phones.
To use it with different devices (e.g. Samsung Gear) it would be nice if this could be configured.

```js
WebVRPolyfill.prototype.enablePolyfill = function() {
  // Initialize our virtual VR devices.
  if (this.isCardboardCompatible()) {
    this.devices.push(new CardboardHMDVRDevice());
  }
```

How about allowing to pass a list of devices to that function? This would probably also require to make the instantiation explicit. What do you think about something along the lines of:
```js
var webVRPolyfill = new WebVRPolyfill();
var deviceList = [new MyDevice()];
webVRPolyfill.enablePolyfill(deviceList);
```
In case no list is passed it could be auto detected.

BTW do you know how WebVR in Chrome will eventually detect what device is used? NFC chip?

**Comment by borismus** [comment]
What's the story with Samsung Gear? Does it have a browser? Right now, isCardboardCompatible just checks that you're on a mobile device.

**Comment by njam** [comment]
Ah I was using Chrome with the Samsung Gear!
I understand now that *experimental Chrome WebVR builds* will use the *Cardboard app*'s HMDVR settings, so it's probably not so needed to add this here…

In case it helps somebody: we've added some functionality to the polyfill which allows us to pass our own HMDVRDevices and skip the WebVR API's one:
https://github.com/cargomedia/webvr-polyfill/pull/1
