### ISSUE TITLE
allow disabling dpdb-fetch

### ISSUE THREAD

**Issue by gmarinov** [borismus/webvr-polyfill#92]
there used to be a WebVRConfig.NO_DPDB_FETCH , no?

**Comment by borismus** [comment]
Yes, but why do you want this?

**Comment by gmarinov** [comment]
1 at Vizor, i'd like us to fetch it manually when we see fit: we get a chance to examine the contents, and a better idea of what parameters our visitors use, without seeking runtime access to their browsers for this purpose
2 it gives away information to a third party
3 in extreme cases it's an attack vector
4 in a complex technical design such as ours, it's one more thing that can fail
