### ISSUE TITLE
Dynamically enabling/disabling the polyfill

### ISSUE THREAD

**Issue by sandromartis** [borismus/webvr-polyfill#95]
Hey there!

Is there a way to dynamically enable or disable the polyfill?

I don't like the polyfill to be active as soon as the script gets added to the HTML page.

For example, it immediately starts overwriting my controls when in mobile mode.
I would like to keep a regular multitouch experience when the user navigates the scene and only switch to VR mode when the user presses a button.

Did I miss something here?

How can I accomplish this with the polyfill?

Thanks,
Sandro

**Comment by cvan** [comment]
Yes, there's an option to do this. Set `window.WebVRConfig = {DEFER_INITIALIZATION: true};`.

See the [configuration docs](https://github.com/borismus/webvr-polyfill#configuration).

**Comment by sandromartis** [comment]
Well I saw that. But is there also a way to turn it off again?

**Comment by sandromartis** [comment]
Okay, I kinda managed to deal with this inside VRControls and VREffect.
Thx.
