### ISSUE TITLE
Set correct canvas CSS size when presenting VR

### ISSUE THREAD

**Issue by brianchirls** [borismus/webvr-polyfill#98]
The latest [`VREffect`](https://github.com/mrdoob/three.js/blob/dev/examples/js/effects/VREffect.js) bundled with three.js (r76+) sets the appropriate canvas size when it receives a `vrdisplaypresentchange` event, but since it does not change the CSS `height` and `width`, it is the wrong size. The `height` is often too small, because it was previously set to `innerHeight`, which leaves room for the URL bar.

It is not `VREffect`'s responsibility to change this, since it assumes it's just submitting frames to the `VRDisplay`, not rendering to the DOM. And now that the polyfill has a wrapper around the canvas that serves as the full screen element, there's extra space left in the wrapper element. I presume it would be the same with other frameworks.

I'd make a pull request, but I'm not sure of the best way to do this. One option is to set the element's inline style dimensions to the full window in VR and then set it back again when exiting presentation. But that can be difficult to get right every time, especially if the canvas is displayed inline and/or doesn't take up the full window. Another option is to use a CSS rule with `!important` for `height` and `width` in the special case of VR presentation, but that feels...icky.

Any ideas?

**Comment by borismus** [comment]
@brianchirls Not sure what you mean here. The example in the polyfill tries to set the size of the VREffect properly based on the vrdisplaypresentchange event: https://github.com/borismus/webvr-polyfill/blob/master/examples/basic/index.html#L162

Even with the latest VREffect, it's ignoring these widths, and using eyeParamsL.renderWidth instead. https://github.com/mrdoob/three.js/blob/dev/examples/js/effects/VREffect.js#L84. Maybe this is the correct thing to do, in which case we need to fix the value the polyfill assigns to HMD.renderWidth.

**Comment by borismus** [comment]
Alternatively, calling renderer.setSize() also fixes the problem. But this seems like a kludge.

**Comment by borismus** [comment]
Ok, I think this should be fixed here: https://github.com/mrdoob/three.js/pull/8800

**Comment by borismus** [comment]
Ok, fixed this in a somewhat lame way. Injecting a CSS class: https://github.com/borismus/webvr-polyfill/blob/master/src/cardboard-vr-display.js#L213, and then applying/unapplying it when changing present mode: https://github.com/borismus/webvr-polyfill/blob/master/src/base.js#L307

**Comment by brianchirls** [comment]
Thanks for doing this @borismus. As I said, this feels totally icky, but as I've been thinking about it, I think the way you implemented it is the right call.

**Comment by toji** [comment]
Minor suggestion: add "position: absolute;" to the class, otherwise the top/bottom/right/left and z-index may not apply.

**Comment by borismus** [comment]
SGTM
